name: WhatsAppClone
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  camera: ^0.6.2+1
  story_view: ^0.12.6
  firebase_core: ^0.5.3
  firebase_auth: ^0.18.4+1
  flutter_multi_formatter: ^1.3.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1

flutter_icons:
  android: true
  ios: true
  image_path: "images/whatsapplogo.png"

flutter:

  uses-material-design: true

  assets:
  - images/whatsapplogo.png
  - images/saburi.jpg
  - images/alyson.jpg
  - images/ana.jpg
  - images/avatar.jpg
  - images/natan.jpg
  - images/vini.jpg
  - images/nat.jpg
  - images/and.jpg
  - images/teste.jpg
  - images/backgroundwpp.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
